### ISSUE TITLE
sse_app() ignores mount prefix, resulting in 404 from client

### ISSUE THREAD

**Issue by allieus** [modelcontextprotocol/python-sdk#412]
**Describe the bug**

When mounting sse_app() from FastMCP with a URL prefix using Starlette’s Mount, the SSE stream still returns the default /messages/ endpoint without the prefix. This causes the MCP client to resolve an incorrect URL (e.g., /messages/ instead of /mcp/messages/), resulting in a 404 error.

**To Reproduce**

1. Define an MCP server as below:

```python
from mcp.server.fastmcp import FastMCP
from starlette.applications import Starlette
from starlette.routing import Mount

mcp = FastMCP(
    # sse_path="/sse",  # default
    # message_path="/messages/",  # default
)


application = Starlette(
    routes=[
        Mount("/mcp", app=mcp.sse_app()),  # HERE !!!
    ]
)
```

2. Start the server and navigate to http://127.0.0.1:8000/mcp/sse in your browser
3. Observe the response in the browser. You will receive an SSE event like:

```
event: endpoint
data: /messages/?session_id=...
```

At this point, the MCP client performs a `urljoin` operation between the SSE URL (http://127.0.0.1:8000/mcp/sse) and the endpoint path (/messages/). This causes the resolved endpoint URL to become http://127.0.0.1:8000/messages/.

4. The client tries to connect to http://127.0.0.1:8000/messages/, which results in a 404.

**Expected behavior**

The SSE stream should return the correct full path reflecting the prefix, e.g.:

```
data: /mcp/messages/?session_id=...
```

This would allow the client to connect to the actual valid message endpoint.

**Screenshots**

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser : Arc
 - Version : 1.87.1 (60573)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser : N/A
 - Version : N/A

**Additional context**

This behavior seems to originate from hardcoded endpoint generation inside sse_app():

https://github.com/modelcontextprotocol/python-sdk/blob/c2ca8e03e046908935d089a2ceed4e80b0c29a24/src/mcp/server/sse.py#L98

It would be great to have support for specifying a prefix in sse_app() or for the prefix to be auto-detected from the ASGI scope.

Thank you!

**Comment by JorgeRuizITCL** [comment]
This might be related with #386

**Comment by richardhundt** [comment]
> This might be related with [#386](https://github.com/modelcontextprotocol/python-sdk/pull/386)

The clients shouldn't be patching the endpoints. The server should just give it the right endpoint during the handshake.

**Comment by earonesty** [comment]
is there any workaround?   

application = Starlette(
    routes=[
        Mount("/", app=mcp.sse_app()),  # HERE !!!
    ]
)

can't get the routes either?

what's the standard way of linking a fastapi/starlette app with mcp?   i need some custom routes

**Comment by pztrick** [comment]
This is all going to change once streamable HTTP lands, but my work-around for now is to just update `/etc/hosts` (MacOS/Linux) or Hosts File Editor (Windows) to add two hostnames `backend` and `mcp`. Then just serve MCP/SSE on only the `mcp` hostname.

Something like:

```
# entrypoint.py
from starlette.applications import Starlette
from starlette.routing import Mount, Host

from django.core.asgi import get_asgi_application
django_http_app = get_asgi_application()

from backend.server import mcp_app

routes = []

application = Starlette(routes=routes)

application.router.routes.append(Host('backend', app=django_http_app))
application.router.routes.append(Host('mcp', app=mcp_app.sse_app()))
```

**Comment by alexellis** [comment]
I ran into this also.

**Comment by rkondra-eightfold** [comment]
Have a potential fix. https://github.com/modelcontextprotocol/python-sdk/pull/524

**Comment by anchen-007** [comment]
I’m experiencing a very similar issue, but in my case, the URL prefix is not defined inside the application code using Mount. Instead, my MCP service is deployed behind an external reverse proxy that uses a multi-level path to distinguish between services.

For example, my SSE server is mounted at /sse, but it's exposed publicly at:
https://****-mcp-server/my/sse

In this case, /my is part of a multi-level URL path added by the reverse proxy, which forwards requests to the root of my MCP server.

When I configure the MCP client to use this kind of multi-level path, I encounter a 404 error.

**Comment by rkondra-eightfold** [comment]
https://github.com/modelcontextprotocol/python-sdk/pull/540 is the latest on this

**Comment by xorcus** [comment]
I just hit the same problem. Could you please consider allowing for the `base_path` to be supplied?
Example modification in `python-sdk/src/mcp/server/fastmcp/server.py`:
```
    def sse_app(self, base_path: str = '') -> Starlette:
        """Return an instance of the SSE server app."""
        sse = SseServerTransport(f'{base_path}{self.settings.message_path}')
```

The original code looks like this:
```
    def sse_app(self) -> Starlette:
        """Return an instance of the SSE server app."""
        sse = SseServerTransport(self.settings.message_path)

        async def handle_sse(request: Request) -> None:
            async with sse.connect_sse(
                request.scope,
                request.receive,
                request._send,  # type: ignore[reportPrivateUsage]
            ) as streams:
                await self._mcp_server.run(
                    streams[0],
                    streams[1],
                    self._mcp_server.create_initialization_options(),
                )

        return Starlette(
            debug=self.settings.debug,
            routes=[
                Route(self.settings.sse_path, endpoint=handle_sse),
                Mount(self.settings.message_path, app=sse.handle_post_message),
            ],
        )
```

Exposing the `base_path` as suggested would allow for mounting with `Starlette` as follows:
```
    Mount('/mcp', mcp.sse_app(base_path='/mcp')),
```

It is a bit redundant, but it works.

**Comment by lizzzcai** [comment]
> I’m experiencing a very similar issue, but in my case, the URL prefix is not defined inside the application code using Mount. Instead, my MCP service is deployed behind an external reverse proxy that uses a multi-level path to distinguish between services.
> 
> For example, my SSE server is mounted at /sse, but it's exposed publicly at: https://****-mcp-server/my/sse
> 
> In this case, /my is part of a multi-level URL path added by the reverse proxy, which forwards requests to the root of my MCP server.
> 
> When I configure the MCP client to use this kind of multi-level path, I encounter a 404 error.

I have the same issue, and I think this should be resolved in client side. Open a feature request for it: https://github.com/modelcontextprotocol/python-sdk/issues/795

**Comment by vikigenius** [comment]
It's still not clear what is supposed to happen from the docs

```python
app = Starlette(
    routes=[
        Mount('/search', app=mcp.sse_app()),
    ]
)
```

When I do this `http://localhost:8000/search/sse` seems to work but `http://localhost:8000/search` gives 404

Is that intended?

**Comment by maxisbey** [comment]
Fixed by #659 — `SseServerTransport` now reads the ASGI `root_path`, so mounted prefixes are respected. The external-reverse-proxy case (where the SDK can't see the prefix) is tracked separately in #795.

<sub>[AI Disclaimer](https://gist.github.com/maxisbey/6123d132484e4c533eab519a2800693d)</sub>
